[tasks.dev-run]
env = { RUST_BACKTRACE = "full" }
command = "cargo"
args = ["run", "${@}"]

[tasks.check-code]
command = "cargo"
args = ["check"]

[tasks.check-fmt]
command = "cargo"
args = ["fmt"]

[tasks.check-lint]
command = "cargo"
args = ["clippy"]

[tasks.check]
dependencies = [
  "check-code",
  "check-fmt",
  "check-lint",
]
